name: Deploy DeltaV to Steam Workshop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Minify Script
      run: |
        mkdir -p dist
        python3 minify.py DeltaV.cs dist/DeltaVFullMinified.cs

    - name: Copy workshop_build.vdf
      run: |
        cp workshop_build.vdf dist/

    - name: Upload to Steam Workshop via SteamCMD (cached session)
      run: |
        cd ~/steamcmd
        ./steamcmd.sh +runscript ~/steamcmd/login.txt

    - name: Commit minified version to main
      run: |
        git config user.name "DeltaV AutoPush"
        git config user.email "autopush@arsnek.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/arsnekfcn/DeltaV.git
        git add dist/DeltaVFullMinified.cs
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Auto-update: pushed new minified Delta-V script [skip ci]"
          git push origin main
        fi
